### ISSUE TITLE
.ini stored hot key settings?

### ISSUE THREAD

**Issue by ATholin** [deivard/WindowQuickSize#1]
Great idea! It looks like a mini [i3wm](https://i3wm.org/)!

Is there any way to make the keybindings persistent in a .ini file, so you won't need to go in the code to change it?

**Comment by deivard** [comment]
Hi ATholin,

Thanks! I actually got some inspiration from i3wm. 

There is as way, but I have no idea how AHK works so I can't do it. I suggest everyone just use my carefully selected keybindings instead of me actually learning to do something.

Thanks, bye.

**Comment by ATholin** [comment]
Hi deivard,

I completely understand your reasoning and agree with all my heart. Your time is obviously more valuable than ours, and I'm terribly sorry for wasting it on this issue.

Good day and how dare I.

**Comment by deivard** [comment]
Hi ATholin,

I am glad you understand me. If I knew how to make a good application, I would not open source it and rely on strangers' pull requests to make it usefull.

Thanks. Bye.
